version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Node.js and npm
      - npm install -g npm@latest
  pre_build:
    commands:
      - echo Installing project dependencies
      - npm install
  build:
    commands:
      - echo Building the React application
      - npm run build
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
